- name: install and start jenkins and docker
  hosts: server
  remote_user: ubuntu
  become: yes

  tasks:
    - name: update repository
      apt:
        name: '*'
        state: latest 

    - name: install git
      apt:
        name: git
        state: present

    - name: download jenkins key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: add jenkins repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins.list


    - name: update package
      apt:
        name: '*'
        state: latest

    - name: Install fontconfig
      shell: apt install fontconfig -y

    - name: Install Java
      shell: apt install fontconfig openjdk-17-jre -y

    - name: install jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
    
    - name: start jenkins
      ansible.builtin.systemd:
        enabled: yes
        name: jenkins
        state: started

    
    - name: update repository for docker
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: upgrading all repository for docker
      apt:
        force_apt_get: yes
        upgrade: yes

    - name: install packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: add docker official gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: update repository for docker
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: install docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: start docker
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started
